### ISSUE TITLE
let's work together on this open sauce

### ISSUE THREAD

**Issue by terinjokes** [bigpipe/sinon-assume#1]
Hey.

I've also been working off-and-on with a sinon plugin for assume. I'd love if we could work together on one thing, rather than making two different implementations.

I pushed it as the work in progress it is to https://github.com/terinjokes/assume-sinon.

**Comment by 3rd-Eden** [comment]
@terinjokes that looks great. @Swaagie is currently on vacation she he'll get back in a week or so. But a collaboration seems to be great way to go here.

**Comment by terinjokes** [comment]
@3rd-Eden Great, looking forward to it.

**Comment by Swaagie** [comment]
back :) @terinjokes totally in favor of a collaboration, duplicating work would be silly indeed. Since you already made a head start it would make sense to continue working on your repo. I don't really mind where the project lives, can always decide later on.

**Comment by Swaagie** [comment]
Created an assume team that has write access to the assume repo, any future plugins could be added to the to team as well. @terinjokes could you provide access to your repo? Going to deprecate this repo

**Comment by Swaagie** [comment]
Will delete this repo entirely as soon as we are done discussing, which is probably soon ;)

**Comment by terinjokes** [comment]
Totally, but I'm also happy if it moves here.

**Comment by Swaagie** [comment]
Let's discuss that when we are done ;) for now let's work on your repo, thanks for providing access
